version: '3.9'
services:
  game_server:
    image: lugobots/server:${SERVER_VERSION:-latest}
    command: play --dev-mode --timer-mode=wait
    ports:
      - "8080:8080"
      - "5000:5000"
    healthcheck:
      test: [ "CMD", "grpc-health-probe", "-addr=game_server:5000" ]
      interval: 300ms
      timeout: 5s
      retries: 100
      start_period: 10s
    depends_on:
      builder:
        condition: service_completed_successfully
  builder:
    image: bot_watcher
    build:
      context: .
      dockerfile: .lugo/builder.Dockerfile
    working_dir: /app
    command: [".lugo/builder.sh"]
    volumes:
      - ./:/app

  player_home_01:
    image: bot_watcher
    command: ["nodemon", "-L", "--config", ".lugo/nodemon.json"]
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - .lugo/venv/lib/python3.9/site-packages:/usr/local/lib/python3.9/site-packages/
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=1
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000

  player_home_02:
    image: bot_watcher
    command: ["nodemon", "-L", "--config", ".lugo/nodemon.json"]
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - .lugo/venv/lib/python3.9/site-packages:/usr/local/lib/python3.9/site-packages/
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=2
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000
  player_home_03:
    image: bot_watcher
    command: ["nodemon", "-L", "--config", ".lugo/nodemon.json"]
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - .lugo/venv/lib/python3.9/site-packages:/usr/local/lib/python3.9/site-packages/
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=3
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000

  player_home_04:
    image: bot_watcher
    command: ["nodemon", "-L", "--config", ".lugo/nodemon.json"]
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - .lugo/venv/lib/python3.9/site-packages:/usr/local/lib/python3.9/site-packages/
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=4
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000

  player_home_05:
    image: bot_watcher
    command: ["nodemon", "-L", "--config", ".lugo/nodemon.json"]
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - .lugo/venv/lib/python3.9/site-packages:/usr/local/lib/python3.9/site-packages/
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=5
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000

  player_home_06:
    image: bot_watcher
    command: ["nodemon", "-L", "--config", ".lugo/nodemon.json"]
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - .lugo/venv/lib/python3.9/site-packages:/usr/local/lib/python3.9/site-packages/
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=6
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000

  player_home_07:
    image: bot_watcher
    command: ["nodemon", "-L", "--config", ".lugo/nodemon.json"]
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - .lugo/venv/lib/python3.9/site-packages:/usr/local/lib/python3.9/site-packages/
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=7
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000

  player_home_08:
    image: bot_watcher
    command: ["nodemon", "-L", "--config", ".lugo/nodemon.json"]
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - .lugo/venv/lib/python3.9/site-packages:/usr/local/lib/python3.9/site-packages/
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=8
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000

  player_home_09:
    image: bot_watcher
    command: ["nodemon", "-L", "--config", ".lugo/nodemon.json"]
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - .lugo/venv/lib/python3.9/site-packages:/usr/local/lib/python3.9/site-packages/
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=9
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000

  player_home_10:
    image: bot_watcher
    command: ["nodemon", "-L", "--config", ".lugo/nodemon.json"]
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - .lugo/venv/lib/python3.9/site-packages:/usr/local/lib/python3.9/site-packages/
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=10
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000

  player_home_11:
    image: bot_watcher
    command: ["nodemon", "-L", "--config", ".lugo/nodemon.json"]
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - .lugo/venv/lib/python3.9/site-packages:/usr/local/lib/python3.9/site-packages/
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=11
      - BOT_TEAM=home
      - BOT_GRPC_URL=game_server:5000

  player_away_01:
    image: lugobots/the-dummies-go:latest
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=1
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
      - BOT_GRPC_INSECURE=true

  player_away_02:
    image: lugobots/the-dummies-go:latest
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=2
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
      - BOT_GRPC_INSECURE=true

  player_away_03:
    image: lugobots/the-dummies-go:latest
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=3
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
      - BOT_GRPC_INSECURE=true
  player_away_04:
    image: lugobots/the-dummies-go:latest
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=4
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
      - BOT_GRPC_INSECURE=true
  player_away_05:
    image: lugobots/the-dummies-go:latest
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=5
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
      - BOT_GRPC_INSECURE=true
  player_away_06:
    image: lugobots/the-dummies-go:latest
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=6
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
      - BOT_GRPC_INSECURE=true
  player_away_07:
    image: lugobots/the-dummies-go:latest
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=7
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
      - BOT_GRPC_INSECURE=true
  player_away_08:
    image: lugobots/the-dummies-go:latest
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=8
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
      - BOT_GRPC_INSECURE=true
  player_away_09:
    image: lugobots/the-dummies-go:latest
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=9
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
      - BOT_GRPC_INSECURE=true
  player_away_10:
    image: lugobots/the-dummies-go:latest
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=10
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
      - BOT_GRPC_INSECURE=true
  player_away_11:
    image: lugobots/the-dummies-go:latest
    depends_on:
        game_server:
          condition: service_healthy
        builder:
          condition: service_completed_successfully
    environment:
      - BOT_NUMBER=11
      - BOT_TEAM=away
      - BOT_GRPC_URL=game_server:5000
      - BOT_GRPC_INSECURE=true

